### PR TITLE
feat(Routing): Enable the snail module

### PR DESCRIPTION
**Pull request by e0ipso**
* [x] Ready for review
* [x] Ready for merge

### CODE REVIEW

**Review by dawehner — APPROVED** [review]
:+1:

**Comment by dawehner** [comment]
Comparing the two broken test runs: https://travis-ci.org/contentacms/contenta_jsonapi/jobs/259473752 and https://travis-ci.org/contentacms/contenta_jsonapi/jobs/265541970 I'm a bit worried that ``` ✖ Testing if element <#block-material-admin-page-title> contains text: "Welcome to Contenta CMS!".  - expected "Welcome to Contenta CMS!" but got: "Page Not Found"``` seems to say something about something more broken.

Am I overestimating the problem here?

**Comment by dawehner** [comment]
@e0ipso thoughts on my analysis?

**Comment by e0ipso** [comment]
This is a valid error. We now have reliable tests.

You can see https://travis-ci.org/contentacms/contenta_jsonapi/jobs/266637705#L1929 that the `/` path is not set on the node for the front page. I'm unsure if the front page configuration option is supposed to be affected by `snail`.

**Comment by dawehner** [comment]
I guess we can close this now?

**Pull request closed without merging**
