### PR TITLE
 Do not modify request with same origin

### PR DESCRIPTION
**Pull request by dawehner**
Task: #76

* [x] Ready for review
* [x] Ready for merge

Let's apply the patch for now, so forms always work, see https://www.drupal.org/node/2853201

### CODE REVIEW

**Review by boztek — APPROVED** [review]
Merges, looks good, patch applies and indeed allows for form submission.

**Review by e0ipso — DISMISSED** [review]
:shipit:

**Review by e0ipso — APPROVED** [review]
Self-approval!

**Comment by dawehner** [comment]
@e0ipso Sorry I was on a run earlier :)

**Pull request merged**
