### PR TITLE
Update CSS selectors in contenta_enhancements.css

### PR DESCRIPTION
**Pull request by imfaber**
Issue: #241

Hi @e0ipso 

The solution I'm proposing here is slightly different from the one I first thought because some of the CSS rules are still good for any theme.

Here the only things that might not work well on any theme are text and background colours therefore, in those cases, we can simply give the `.material_admin` context.

### CODE REVIEW

**Comment by e0ipso** [comment]
Thanks for the PR! Can you please provide a before and after screenshots?

**Comment by briancwald** [comment]
@e0ipso for styling related to material_admin specifically, maybe we should just add that to material_admin itself. I have made the decision that to do a real admin theme where I work with form elements, I am going to need to support some contrib modules. 

[(see the ones I have added so far)](https://github.com/briancwald/material_admin/tree/8.x-1.x/scss/components/contrib)


The reason I suggest this for these specific changes is due to the color declarations. I have added in some underlying support to handle [color palettes](https://github.com/briancwald/material_admin/blob/8.x-1.x/scss/_color_schema.scss), so hardcoded CSS reference to colors may produce strange pages.

If I add it to material_admin I can [use the sass variables ($prmary, $seconday, $utility, etc)](https://github.com/briancwald/material_admin/blob/8.x-1.x/scss/_settings.scss#L61) which if replaced will still work great for your pages.

**Comment by e0ipso** [comment]
@briancwald is this something you can take on, or you need assistance from @imfaber for that?

**Comment by briancwald** [comment]
@e0ipso I am happy to do that if you agree that is the best route? If you feel it makes more sense to leave it in the module, then id say this PR looks ok.

**Comment by e0ipso** [comment]
@briancwald I think that it makes sense to move it upstream instead of having it in Contenta. This will benefit others.

On a separate note, do you want to move the views integration to generate a list of cards into the theme/editorial module? I think that could make sense too. Please don't be horrified by my theming skills https://github.com/contentacms/contenta_jsonapi/blob/8.x-1.x/modules/recipes_magazin_contenta/templates/views-view-grid.html.twig

**Comment by e0ipso** [comment]
@briancwald did you end up grabbing changes here for the admin theme? Should I commit this instead?

**Comment by briancwald** [comment]
@e0ipso yes I have made all those these changes to the dev branch. I will create a new alpha release today after I run through QA testing.

Note - 
` .material_admin .card-content > .fa ` 

I believe this is legacy code from pre Alpha release - when I was using the Font Awesome library, which is no longer part of the build (uses material-icons) - so I did not do anything for that one.

**Comment by briancwald** [comment]
Also - I missed this message

> On a separate note, do you want to move the views integration to generate a list of cards into the theme/editorial module? 

I agree on this, and I am working on a twig template for generic use but a views formatter would be good too. I believe that would need to happen in the support module though, I dont think themes can create formatters (will confirm that).

**Comment by e0ipso** [comment]
This was included via the theme.

**Pull request closed without merging**
