### PR TITLE
Add openapi

### PR DESCRIPTION
**Pull request by dawehner**
Task: 

* [x] Ready for review
* [x] Ready for merge

### Notes

Potential followups: Provide redoc/swaggerUI instead of docson as module

### Test Instructions

* Build it
* Login
* Goto ```http://localhost:8888/openapi/jsonapi?_format=json``` and download the result
* Goto http://editor.swagger.io/ and import the jsonapi.json file

### QA

screen shot 2017-06-19 at 18 57 54

### CODE REVIEW

**Comment by e0ipso** [comment]
Did you try the redoc submodule? Worth enabling it by default?

This looks waaaay better than Docson.

**Comment by dawehner** [comment]
Oh I haven't tried it yet

**Comment by dawehner** [comment]
I really like it: 
screen shot 2017-06-19 at 20 05 50

**Comment by dawehner** [comment]
Let's add redoc here as well.

**Comment by e0ipso** [comment]
Can you add a follow up to remove Docson. I'll work on it.

**Pull request merged**
