### PR TITLE
Provide a single source of truth for the consumers

### PR DESCRIPTION
**Pull request by dawehner**
Task: 

* [x] Ready for review
* [x] Ready for merge

... description

### Notes

... Notes-optional

### Test Instructions

Test-instructions

### QA

... Screenshots/Screencasts-optional

### CODE REVIEW

**Comment by e0ipso** [comment]
@dawehner any idea why the build is broken?

**Comment by dawehner** [comment]
```

PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///home/travis/.phpenv/versions/5.6.24/bin/composer/src/Composer/DependencyResolver/Pool.php on line 205
```

These are 1.6 GB, something seriously weird is going on.

**Comment by e0ipso** [comment]
> These are 1.6 GB, something seriously weird is going on.

Whaaat? We need to fix this asap.

**Comment by e0ipso** [comment]
I merged since it seems obvious that this PR is not causing the memory issues.

**Pull request merged**
