### PR TITLE
Consider adding Relative Path to Absolute URLs module when formatted fields will expose processed value

### PR DESCRIPTION
**Pull request by spleshka**
Hey guys. 

I'm working with headless D8 quite a lot, and every second project has blog, news, etc - dynamic content maintained by content editors. They love adding pictures and other files into the content body through WYSIWYG. Unfortunately, WYSIWYG inserts relative URLs to those files into the content, so when the content is being displayed from another server / domain, these files / images have broken URLs. 

I suggest to add [REST Absolute URLs](https://www.drupal.org/project/rest_absolute_urls) to Contenta CMS and have it enabled by default. It will make users experience slightly better :)

What's  your opinion on this?

Cheers,
Ev.

### CODE REVIEW

**Comment by dawehner** [comment]
This looks like an excellent idea for me!

**Comment by dawehner** [comment]
@e0ipso  What do you think about this one?

**Comment by e0ipso** [comment]
I haven't had the chance to review the module's code. However, this is @spleshka's module so it must be just fine :-)

**Comment by spleshka** [comment]
Hi guys! Even though I'd love to see the module in Contenta, I believe there's a better solution. As soon as formatted fields will expose processed values to the frontend, I'd recommend using https://www.drupal.org/project/rel_to_abs instead.

**Comment by e0ipso** [comment]
That makes sense. Thanks for looping back in this.

**Comment by spleshka** [comment]
My pleasure :) I'll update the issue title toward the new solution.

**Comment by dawehner** [comment]
My only problem is: You can lo longer to a GET and a POST and be idepotent,
but maybe this argument is a bit too strc
Evgeniy <notifications@github.com> schrieb am Fr., 24. Nov. 2017 um
14:54 Uhr:

**Comment by e0ipso** [comment]
> You can lo longer to a GET and a POST and be idepotent

That's a big issue IMO.

**Comment by spleshka** [comment]
Very good point. Though I'm wondering how many people edit content on the backend, send to the frontend and then save it there. Usually the content is ediable either on the FE or BE. I'd consider this as an issue to resolve next.

**Comment by dawehner** [comment]
Yeah, I think absolute paths are perfect for read only applications.

Evgeniy <notifications@github.com> schrieb am Fr., 24. Nov. 2017 um
15:19 Uhr:

**Comment by e0ipso** [comment]
Idempotency is something important. People will have to install that module by themselves if they need it.

**Pull request closed without merging**
