### PR TITLE
Remove invalid recipe from recipes_magazin

### PR DESCRIPTION
**Pull request by mortenson**
* [x] Ready for review
* [x] Ready for merge

When I installed contentacms using the install script, I did not receive any default content. After some troubleshooting, I found that there was an invalid recipe in the recipes_magazin module, which was causing the recipes_magazin__recipes migration to fail. This PR removes the invalid recipe.

### Test Instructions

If you build contentacms from 8.x-1.x you should not receive any default content. If you build from the 8.x-fix-recipes branch, default content should work.

### CODE REVIEW

**Comment by e0ipso** [comment]
I'm OK removing a recipe if that fixes migration problems. Did you track why this recipe was invalid?

**Comment by mortenson** [comment]
@e0ipso It has unescaped newlines, references an image that doesn't exit (`Kibbeh_with_mint.jpg`), and doesn't appear to be brought over from cookipedia as the other recipes are.

**Comment by dawehner** [comment]
Something changed this image is in the repo, isn't it?

**Comment by mortenson** [comment]
@dawehner It was deleted in #46 (https://github.com/contentacms/contenta_jsonapi/pull/46/files#diff-847622c5dce0e76032d82d2ecc54fba7)

**Comment by dawehner** [comment]
Oh. Should we maybe add it back?

**Comment by mortenson** [comment]
If you want an example of a local recipe we can, but I like that everything is coming from one source now. Up to you 😄

**Pull request merged**
