### PR TITLE
#113 Add option for tutorial topic of "GraphQL"

### PR DESCRIPTION
**Pull request by pixelmord**
See issue #113

Task: #123

* [x] Ready for review
* [x] Ready for merge

... description

### Notes

... Notes-optional

### Test Instructions

Test-instructions

### QA

... Screenshots/Screencasts-optional

### CODE REVIEW

**Comment by dawehner** [comment]
@pixelmord @e0ipso and myself discussed that a bit and we thought it would be great if you could make your PRs against some kind of feature branch. With that we can ensure to not let consumers distract too much, while you and I hope others, can flesh out graphql a bit.

What do you think about this plan?

**Comment by pixelmord** [comment]
Good idea @dawehner just let me know what branch.

I created a "contenta_react_apollo_graphql" consumer, I could push that to a repo in this organisation so we can have something to integrate with?

I have not so much experience with that and looking through @fubhy 's excellent but complex drupal-decoupled-app always gives me a bit of a vertigo, so I started with something slightly less complex: https://reactql.org/

**Comment by dawehner** [comment]
This branch name totally works for me.

**Comment by pixelmord** [comment]
@dawehner You understood me wrong, may be due to the fact that I mentioned the thing about the consumer client app.
If you want me to do this pull request (and one that has the contenta_graphql module) against a feature branch, then you yourself need to create a new branch on this repo because I am not a member of this organisation ;)
Why not name it "feature/contenta_graphql"

**Comment by e0ipso** [comment]
Let's hope we can get that topic populated soon!

**Comment by e0ipso** [comment]
Thanks all!

**Pull request merged**
