### PR TITLE
full documentation about how pages should be built by consumers

### PR DESCRIPTION
**Pull request by yann-yinn**
Task: #123

* [x] Ready for review
* [x] Ready for merge

... description

### Notes

... Notes-optional

### Test Instructions

Test-instructions

### QA

... Screenshots/Screencasts-optional

### CODE REVIEW

**Comment by cjgratacos** [comment]
@nyl-auster Awesome job with the documentation 👍.

**Comment by cjgratacos** [comment]
@nyl-auster we should squash the commits before merging the PR.

**Comment by yann-yinn** [comment]
@cjgratacos oups don't know how to do that.  I will take a look when i have time...

**Comment by dawehner** [comment]
Thank you @nyl-auster . Sorry for not coming back to it earlier.
I fixed a couple of small things I found. Let's merge it in and continuously improve it.

**Pull request merged**
