### PR TITLE
Removed stack cors patches that don't apply anymore.

### PR DESCRIPTION
**Pull request by recidive**
See issue #199.

### CODE REVIEW

**Comment by dawehner** [comment]
Don't we need https://github.com/asm89/stack-cors/pull/42 at least still? Can we maybe try to update our patches somehow?

**Comment by simesy** [comment]
Not sure if you are aware (you may prefer to commit to a local patches directory) but instead of a copy of the patch at https://github.com/asm89/stack-cors/pull/42 you can add `.patch` to the end, and you'll get:

```
    "patches":{
        "asm89/stack-cors": {
            "....": "https://patch-diff.githubusercontent.com/raw/asm89/stack-cors/pull/42.patch"
        }
    },
```

**Comment by simesy** [comment]
I just realised that i may have commented in the wrong place, sorry!

**Comment by e0ipso** [comment]
This was done.

**Pull request closed without merging**
