### PR TITLE
feat(DX): Add resource mappings for consumers and tutorials

### PR DESCRIPTION
**Pull request by e0ipso**
* [x] Ready for review
* [x] Ready for merge

Adds nicer resources for tutorials and consumers.

### CODE REVIEW

**Comment by dawehner** [comment]
Interesting ... from a product poit of view exposing the consumers feels weird. Would one do that on a real life project?

**Comment by e0ipso** [comment]
I think that it's interesting to the Contenta consumers to be able to consult their own UUID.

**Comment by dawehner** [comment]
Interesting point. I'm wondering whether some information about the
consumer should be carried around as part of the authentication somehow
instead ...

**Comment by e0ipso** [comment]
I am going to back off from this one. I don't think this has much value beyond an admin interface to list consumers, but Contenta is not focused on that.

**Pull request closed without merging**
