### PR TITLE
feat(API): Clean the embeddables resource

### PR DESCRIPTION
**Pull request by e0ipso**
Makes the API consistent with the rest of the resources.

* [x] Ready for review
* [x] Ready for merge

... description

### Notes

... Notes-optional

### Test Instructions

Test-instructions

### QA

... Screenshots/Screencasts-optional

### CODE REVIEW

**Comment by dawehner** [comment]
WFM, I have not yet used the embeddable. To be honest I think we should talk a bit about the content model maybe with @eaton before we continue on embeddables ...

**Comment by e0ipso** [comment]
I'm good with reevaluating the content type. However I think that we should either:

  - Pull out the content type until it's decided.
  - Or make the API for the temporary content type consistent.

**Comment by dawehner** [comment]
> Or make the API for the temporary content type consistent.

I think this would be a good idea!

**Comment by e0ipso** [comment]
@dawehner the whole resource has been disabled now. However I left the API modifications in so they can take effect when the resource is re-enabled.

**Comment by dawehner** [comment]
That is a nice idea. Let's get it in 🛳

**Pull request merged**
