### PR TITLE
feat(UI): Remove custom theme

### PR DESCRIPTION
**Pull request by e0ipso**
* [x] Ready for review
* [x] Ready for merge

`82 additions and 47,632 deletions.` describes accurately the intent here.

We want to remove the need of a front-end theme for only 2 front-end pages. Specially when the admin theme is *SO* similar.

### QA

New look of the front-end pages.

tutorials contenta json api 2017-07-17 08-36-48
tutorials contenta json api 2017-07-17 08-37-09
welcome to contenta cms contenta json api 2017-07-17 08-37-29
welcome to contenta cms contenta json api 2017-07-17 08-37-45

welcome to contenta cms contenta json api 2017-07-17 08-38-42
tutorials contenta json api 2017-07-17 08-39-27

### CODE REVIEW

**Comment by e0ipso** [comment]
@ckrina @dawehner I think this movement is totally worth it to remove bloat from the distro.

**Comment by dawehner** [comment]
I love it. For some reason my brain like blue more anyway ...

Notes:

* The frontpage has an empty bar: 
screen shot 2017-07-17 at 10 14 29
* We still waste a LOT of vertical space, IMHO
* Is it just me that "About tutorials" has a wrong background colour now, still?

**Comment by dawehner** [comment]
I'd love to see feedback from others first, but in general +1 and we can continue to iterate later.

**Comment by e0ipso** [comment]
> The frontpage has an empty bar:
> We still waste a LOT of vertical space, IMHO

These two will be addressed by #134

> Is it just me that "About tutorials" has a wrong background colour now, still?

I don't see it. What do you mean?

**Comment by dawehner** [comment]
> I don't see it. What do you mean?

Well the dark green seem to not fit properly with the blue

**Comment by e0ipso** [comment]
> Well the dark green seem to not fit properly with the blue

Ah! That dark green is not the header, it's the highlighted pane. I changed it to blue in 68aab07.

tutorials contenta json api 2017-07-17 12-49-05

**Comment by dawehner** [comment]
Much better! Thank you

Should we maybe for @ckrina to give a thumbs up?

**Comment by e0ipso** [comment]
> Should we maybe for @ckrina to give a thumbs up?

I'd rather do follow ups because big PRs get unmaintainable quickly.

**Comment by ckrina** [comment]
It looks much better now! We could change anything in the future, but it is a great improvement!

**Comment by briancwald** [comment]
FWIW I will be adding a custom implementation of the ole 'color' module which will allow you to create (or choose) a different palette. so you could have a Contenta palette that happens on install.

**Comment by briancwald** [comment]
Also, removing a front end theme and using material_admin as both gives you OOTB 'portal' style login/register page which helps articulate the backend CMS style project.

screenshot 2017-07-24 17 48 24

(also, you changing the default logo to contenta on install for this would be nice.)

**Comment by e0ipso** [comment]
> I will be adding a custom implementation of the ole 'color' module

That's so great!

**Pull request merged**
