### PR TITLE
Provide articles upon installation

### PR DESCRIPTION
**Pull request by dawehner**
Task: #99

* [x] Ready for review
* [x] Ready for merge

Includes the following items:

* A migration for articles
* 3 example articles from http://www.foodista.com/

### CODE REVIEW

**Comment by dawehner** [comment]
@e0ipso Do you think we can merge this?

**Comment by e0ipso** [comment]
Absolutely. I was thinking that Suzi may be working on top of this. But no
reason to block it.

**Comment by dawehner** [comment]
I was quite sure she posted somewhere, but I really no longer know where :(

**Review by e0ipso — APPROVED** [review]

**Comment by suzi** [comment]
I'll follow up in the issue (pretty sure that's where i commented before) and add some more articles. this looks great!

**Comment by dawehner** [comment]
🎆

**Pull request merged**
