### PR TITLE
Grant "access user profiles" permission to all users by default in recipes_magazin_contenta

### PR DESCRIPTION
**Pull request by TuWebO**
Task: #98 

* [x] Ready for review
* [] Ready for merge

We want to be able to access author information as an anonymous and/or authenticated user.
This means that installing **recipes_magazin_contenta** module (which can be activated during the installation, if _Install the demo content_ checkbox is checked) will grant **View user information** ( "access user profiles") access to any user. 

### Notes
Review of the code is needed since task comment says:

> This should go into the recipes_magazin_contenta module so it can be uninstalled when the default content is yanked.

The approach followed here will grant permissions but is doing nothing when uninstalled, so I don't know if I am following the right approach, help here would be great.

### Test Instructions

1. Checkout fb-recipies-magazin-contenta branch.
2. Install profile checking _Install the demo content_ option (by default).
3. After install is complete, as an anonymous user navigate to a recipient content
4. Check that you can see the link to the user and can open that link
5. Repeat operation with an authenticated user

### QA

1. Is it the right way to implement it?
2. If this is the right way, should we aware the user that installing this module will perform this grant permissions action?

... Screenshots/Screencasts-optional
contenta-si-01-install-demo-content
contenta-si-02-check-user-permissions-after-install
contenta-si-03-anon-view-content-user-link
contenta-si-04-anon-view-user-account

### CODE REVIEW

**Review by e0ipso — CHANGES_REQUESTED** [review]
Can we do this with a configuration export in the recipes_magazin_contenta?

**Comment by TuWebO** [comment]
Hello,
I've been doing some tests:

1. Add user configuration files to **config/install**, this will throw an error:
`Configuration objects (user.role.anonymous, user.role.authenticated) provided by recipes_magazin_contenta already exist in active configuration... ` Since the profile is already declaring them (I guess).

2. Add user configuration files to **config/optional**, this seems to do nothing, I guess it detects the configuratiton already exists in the contenta_jsonapi profile and then it doesn't apply.

Now wondering what solution could be the best one. Using hook_install seems to not be recomemded or best practice. Any ideas?

**Comment by e0ipso** [comment]
Hmmm, you are right. It's hard to merge configuration from 2 different scopes.

**Comment by TuWebO** [comment]
I have to explore third_party_settings, I didn't know about it. I just pointing out here so don't forget it.

**Comment by e0ipso** [comment]
@TuWebO I'm wondering if you had any success with the `third_party_settings`.

**Comment by TuWebO** [comment]
@e0ipso didn't check it too much third party setttings, I was checking how profiles and modules can overwrite configuration, it seems that profiles can do that, modules don't.
I am learning configuration in profiles and modules, it is not easy and there is a lot of ongoing work, since I am learning now I might be focusing on topics in the wrong way.

**Comment by e0ipso** [comment]
That sounds great. Thanks for the update.


[image: --]

Mateu Aguiló Bosch
[image: https://]about.me/e0ipso
<https://about.me/e0ipso?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

**Comment by wimleers** [comment]
This scared me for a second, then I realized this only applies to `recipes_magazin_contenta` :) I can't change the title, but that'd be a good clarification.

**Comment by e0ipso** [comment]
Changed @wimleers.

Thanks for taking time to scan this issue queue.

**Comment by e0ipso** [comment]
I'm going to close this, as it's stale.

**Pull request closed without merging**
