### PR TITLE
Create temporary key pair and Simple OAuth client

### PR DESCRIPTION
**Pull request by chris-hamper**
Task: #56

* [ ] Ready for review
* [ ] Ready for merge

Creates a temporary RSA key pair and demo OAuth2 client.

### Notes

Not quite working yet.

It seems that the Simple OAuth module is not yet installed when `contenta_jsonapi_install()` is called. Therefore, the configuration created in the `_install()` is not able to be saved.

In Reservoir, the modules are installed via the profile's .info.yml file's `dependencies`. I'm guessing this is why the code this PR is based on works there. What is the reasoning behind doing the config install in Contenta? I've never encountered that approach before.

Is there a workaround for this?

### Test Instructions

1. Install Contenta
1. Browse to `/admin/config/people/simple_oauth` and verify keys and timeouts are set
1. Browse to `/admin/config/people/simple_oauth/oauth2_client` and verify "demo app" client exists

### CODE REVIEW

**Comment by dawehner** [comment]
> In Reservoir, the modules are installed via the profile's .info.yml file's dependencies. I'm guessing this is why the code this PR is based on works there. What is the reasoning behind doing the config install in Contenta? I've never encountered that approach before.

Yeah, that is the old/hard way of creating install profiles :) The way how especially @alexpott sees installation profiles is basically a fully working configuration and that's it. The rest is handled in modules. In an ideal future install profiles would not be something the runtime depends on, even well, it is right now, sadly. Which is a clusterfuck to say the least.

I guess you could put it into https://github.com/contentacms/contenta_jsonapi/tree/8.x-1.x/modules/contenta_enhancements as that module also enables CORS by default.

**Comment by chris-hamper** [comment]
Thanks, I'll give that suggestion a try. It seems like that should work.

**Comment by chris-hamper** [comment]
I tried moving the code into `contenta_enhancements` without success. The key files are generated as before, but it seems like the configuration just isn't being set during install. Disabling and reinstalling the `contenta_enhancements` module does successfully set the configuration values, though.

At this point I'm not sure what else to do, other than maybe writing out a `simple_oauth.settings.yml` file on the fly during install, so that it is incorporated in during the config sync. I'm not even sure if the sequence of events would be right for that, and it just plain feels icky.

**Comment by dawehner** [comment]
Here is just an idea in my head.

What about doing the following:

* Providing a drush commands to generate a key pair/add the oauth2 client
* Allow people to use this drush command in general
* Use this drush command at the end of the installer

Yes this sounds like a workaround, but I also think that the drush command could be useful in general.

**Comment by chris-hamper** [comment]
Sounds good! I had actually pondered doing that for the Simple OAuth module, itself, at one point, and had completely forgotten about it! I think I had let go of the idea because I wasn't certain it made sense doing things that way.

**Comment by dawehner** [comment]
It certainly requires some level of thinking about security, maybe warn
people that this is a common which is meant to be run locally.

chris-hamper <notifications@github.com> schrieb am Do., 29. Juni 2017 um
13:24 Uhr:

**Comment by e0ipso** [comment]
> Sounds good! I had actually pondered doing that for the Simple OAuth module, itself, at one point, and had completely forgotten about it! I think I had let go of the idea because I wasn't certain it made sense doing things that way.

This would be a great addition to Simple OAuth! The only gotcha is that then we inherit all the dependency checking to create the keys in Simple OAuth. I'm good with that since it only affects the `drush` command.

**Comment by greg-1-anderson** [comment]
The [Terminus Build Tools Plugin](https://github.com/pantheon-systems/terminus-build-tools-plugin) has some [code to create ssh keys](https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/master/src/Task/Ssh/CreateKeys.php) and apply them to different services (e.g. Circle CI).

Maybe not a huge accellerator for you, but thought I'd link to it anyway. My plan is to factor those classes out into a project of Robo tasks for service configuration. Might be nifty to have a Contenta key receiver.

**Comment by dawehner** [comment]
That is super nice. Thank you greg for letting us know!

Greg Anderson <notifications@github.com> schrieb am Mo., 10. Juli 2017 um
20:09 Uhr:

**Comment by e0ipso** [comment]
Simple OAuth added support for this recently. Make sure to update Reservoir if necessary @chris-hamper @wimleers @tedbow.

**Pull request closed without merging**
